# Path to yjp-probe-api-redist.jar within your YourKit installation.
# E.g., /opt/YourKit-JavaProfiler-2025.9/lib/yjp-probe-api-redist.jar
yourkitProbeApiJar=/path/to/yjp-probe-api-redist.jar

# Path to the YourKit agent for your specific platform.
# E.g., /opt/YourKit-JavaProfiler-2025.9/bin/linux-x86-64/libyjpagent.so
# For help, see https://www.yourkit.com/docs/java/help/agent.jsp
yourkitAgent=/path/to/yourkit/agent
